# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: setup
description: setup node environment

runs:
  using: 'composite'
  steps:
    - name: install node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: install dependencies
      shell: bash
      run: npm ci
