# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: ☀️

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: continuous-integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    uses: cascadeplus/cascade/.github/workflows/run.yml@main
    with:
      command: format:check

  lint:
    uses: cascadeplus/cascade/.github/workflows/run.yml@main
    with:
      command: lint:check

  build:
    uses: cascadeplus/cascade/.github/workflows/run.yml@main
    with:
      command: build

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cascadeplus/cascade/.github/actions/install@main
      - run: npm run test:unit
      - uses: codecov/codecov-action@v3
