# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: ☀️

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: continuous-integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: /
    uses: cassiecascade/houseplant/.github/workflows/check.yml@main

  build:
    name: /
    uses: cassiecascade/houseplant/.github/workflows/build.yml@main

  unit:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        uses: ./.github/actions/setup

      - name: test
        run: npm run test:coverage

      - name: coverage reports
        uses: codecov/codecov-action@v3
